# Generated by Django 5.0.6 on 2024-07-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('nombre_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('f_nacimiento', models.DateField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.FileField(blank=True, default='avatars/default.jpg', upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EL', 'Electrónica'), ('RO', 'Ropa'), ('AL', 'Alimentos'), ('LI', 'Libros')], default='EL', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_trabajo', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('grupo_trabajo', models.ManyToManyField(related_name='personal', to='core.grupotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad_producto', models.IntegerField(blank=True, default=0, null=True)),
                ('precio_producto', models.IntegerField(blank=True, default=0, null=True)),
                ('grupo_trabajo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.grupotrabajo')),
            ],
        ),
    ]
